version: '2.2'
services:

  django:
    container_name: land-collection
    image: landcollection:latest
    env_file: .env
    build:
      dockerfile: ./Dockerfile
      context: /app
      target: builder
    ports: 
      - '8000:8000'
    networks:
    - website
    volumes:
    - static_volume:/app/staticfiles

networks:
  website:
    driver: bridge

volumes:
  static_volume: