version: '2.2'
services:
  nginx:
    container_name: nginx-dev
    image: nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - nginx_network
    volumes:
      - static_volume:/app/staticfiles
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']

  django:
    container_name: land-collection-dev
    image: landcollection:latest
    env_file: ../.env
    build:
      dockerfile: ../app/Dockerfile
      context: ../app
      target: builder
    ports: 
      - '8000:8000'
    networks:
    - nginx_network
    volumes:
    - static_volume:/app/staticfiles

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
